name: application
description: "A new Flutter-project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8

  # Network.
  http: 1.2.2
  get_it: 8.0.2

  # Storage.
  shared_preferences: 2.3.3

  # Navigation.
  auto_route: 9.2.2

  # UI.
  flutter_screenutil: 5.9.3

  # State Management.
  equatable: 2.0.7
  bloc: 8.1.4
  flutter_bloc: 8.1.6

  # Serialization.
  json_serializable: 6.9.0
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0

  # Code Generation.
  auto_route_generator: 9.0.0
  build_runner: 2.4.13

flutter:
  uses-material-design: true
